### ISSUE TITLE
Use CSS `font-variant-numeric` to display numbers

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#172]
Following [this article](https://blog.usejournal.com/proportional-vs-monospaced-numbers-when-to-use-which-one-in-order-to-avoid-wiggling-labels-e31b1c83e4d0) it's worth to check if `font-variant-numeric` can improve the readability of numbers:

```css
.yourcssclass {
  font-variant-numeric: tabular-nums;
}
```

![](https://miro.medium.com/max/720/1*5Hy8C28ZA4Scy8evCfSZSA.gif)
